# Generated by Django 6.0.2 on 2026-05-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0005_expenseslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseslist',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
