# Generated by Django 6.0.2 on 2026-05-02 05:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0006_expenseslist_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeExpensesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_model_name', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('petrol_amount', models.IntegerField(default=0)),
                ('start_trip', models.IntegerField(default=0)),
                ('end_trip', models.IntegerField(default=0)),
                ('mileage', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
