# Generated by Django 6.0.2 on 2026-05-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0007_bikeexpenseslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseslist',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10),
        ),
    ]
