# Generated by Django 6.0.2 on 2026-05-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0008_expenseslist_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseslist',
            name='type',
        ),
    ]
