# Generated by Django 6.0.2 on 2026-05-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0010_bank_expenseslist_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='user',
        ),
    ]
