# Generated by Django 6.0.2 on 2026-05-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0011_remove_bank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseslist',
            name='bank',
            field=models.CharField(max_length=100),
        ),
    ]
