# Generated by Django 6.0.2 on 2026-05-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0012_alter_expenseslist_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseslist',
            name='extra_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
