# Generated by Django 6.0.2 on 2026-05-16 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0014_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_bank_transfer', to='expense_app.bank')),
                ('to_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_bank_transfer', to='expense_app.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
