# Generated by Django 6.0.2 on 2026-05-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0015_selftransfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelfTransfer',
        ),
    ]
