# Generated by Django 6.0.2 on 2026-05-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0016_delete_selftransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeexpenseslist',
            name='insurance_image',
            field=models.ImageField(blank=True, null=True, upload_to='ins_img/'),
        ),
        migrations.AddField(
            model_name='bikeexpenseslist',
            name='licence_image',
            field=models.ImageField(blank=True, null=True, upload_to='lice_img/'),
        ),
        migrations.AddField(
            model_name='bikeexpenseslist',
            name='rc_image',
            field=models.ImageField(blank=True, null=True, upload_to='rc_img/'),
        ),
    ]
