# Generated by Django 6.0.2 on 2026-05-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0017_bikeexpenseslist_insurance_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeexpenseslist',
            name='bike_model_name',
        ),
        migrations.AddField(
            model_name='bikeexpenseslist',
            name='bike_image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_image/'),
        ),
    ]
