# Generated by Django 6.0.2 on 2026-05-30 10:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0018_remove_bikeexpenseslist_bike_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('petrol_amount', models.IntegerField(default=0)),
                ('start_trip', models.IntegerField(default=0)),
                ('end_trip', models.IntegerField(default=0)),
                ('mileage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
